name: Playwright Tests
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
    paths-ignore:
      - "/Users/manojkanchana/PlaywrightTest_2026/.github/*"  #this will ignore triggering the event when a PR is raised just to update .github files (Here it's .yml)
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test name to run'
        required: true
        default: 'smoke'
        type: string
      run_allure:
        description: 'Generate Allure Report?'
        required: true
        default: true
        type: boolean
      workers:
        description: 'Parallel workers'
        required: true
        default: 3
        type: number
      test_script:
        description: 'Test script to run'
        required: true
        default: 'regression'
        type: choice
        options:
          - regression
          - letsShop_PlaceOrder
          - bookAnEvent_test
          - singleEventWithRefund_test
          - groupTicketBooking_test

jobs:

  # =======================================================
  # JOB 1: Run Playwright Tests in Parallel Shards
  # =======================================================
  set-up_test:
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      # fail-fast: true
      matrix:
        node_versions: [24]
        shard-index: [1,2,3]
        shard-total: [3]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v4

      - name: Load & Cache Dependencies #Custom Action Loaded from Local
        uses: ./.github/actions/cached-deps # Path of the Custom Actions repo 
        with:
          caching: 'true'

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Playwright tests
      #  env:
      #    PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}
      #  run: npx playwright test --config=playwright.service.config.ts --workers= ${{ inputs.workers || 3}}
        run: npm run ${{ inputs.test_script || 'regression' }} --shard=${{ matrix.shard-index }}/${{ matrix.shard-total }}

      - uses: actions/upload-artifact@v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: all-blob-reports-shard-${{ matrix.shard-index }}
          path: blob-report/
          retention-days: 7

  # Dummy deploy to reuse another workflow - using 'uses' and the relative path to the reusable YAML file.
  deploy:
    needs: set-up_test
    uses: ./.github/workflows/reusableWorkflow.yml
    with:
      artifact_name: playwright-report

  # =======================================================
  # JOB 2: Merge Blob Reports & Send Slack Notification
  # =======================================================
  report:
    name: Merge Reports & Notify
    if: !cancelled()
    needs: [set-up_test, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Load & Cache Dependencies #Custom Action Loaded from Local
        uses: ./.github/actions/cached-deps # Path of the Custom Actions repo 
        with:
          caching: 'true'
        
      # Download all blob artifacts uploaded by the test job shards
      - name: Download Blob Reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: all-blob-reports-*
          merge-multiple: true
