name: Playwright Tests
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
    paths-ignore:
      - ".github/**"  #this will ignore triggering the event when a PR is raised just to update .github files (Here it's .yml)
  schedule:
    - cron: '30 18 * * 1,5'
  
#env:
    #NODE_VERSION: '24' #To make node version available globally across all jobs, we defined under env.

jobs:

  # =======================================================
  # JOB 1: Run Playwright Tests in Parallel Shards
  # =======================================================
  set-up_test:
    if: github.event.pull_request.merged == true
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        # node_versions: [24]
        shard-index: [1,2,3]
        shard-total: [3]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v6

      - name: Load & Cache Dependencies #Custom Action Loaded from Local
        uses: ./.github/actions/cached-deps # Path of the Custom Actions repo 
        with:
          caching: 'true'
          # Read from repository vars context
          node-version: ${{ vars.DEFAULT_NODE_VERSION }}

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Playwright tests
        continue-on-error: true
      #  env:
      #    PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL 
      #  run: npx playwright test --config=playwright.service.config.ts --workers= ${{ inputs.workers || 3
        run: npm run regression -- --shard=${{ matrix.shard-index }}/${{ matrix.shard-total }}

      - uses: actions/upload-artifact@v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: all-blob-reports-shard-${{ matrix.shard-index }}
          path: blob-report/
          retention-days: 7

  # =======================================================
  # JOB 2: Merge Blob Reports & Send Slack Notification
  # =======================================================
  report:
    needs: set-up_test
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/reusableWorkflow.yml
    with:
      artifact_name: 'all-blob-reports'
      node-version: ${{ vars.DEFAULT_NODE_VERSION }}
      retentionDays: 30
