name: Playwright Tests
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
    paths-ignore:
      - "/Users/manojkanchana/PlaywrightTest_2026/.github/*"  #this will ignore triggering the event when a PR is raised just to update .github files (Here it's .yml)
  workflow_dispatch:

jobs:
  set-up_test:
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      # fail-fast: true
      matrix:
        node_versions: [22, 24]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v4

      - name: Load & Cache Dependencies #Custom Action Loaded from Local
        uses: ./.github/actions/cached-deps # Path of the Custom Actions repo 

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}
        run: npx playwright test --config=playwright.service.config.ts --workers=4

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

  # Dummy deploy to reuse another workflow - using 'uses' and the relative path to the reusable YAML file.
  deploy:
    needs: set-up_test
    uses: ./.github/workflows/reusableWorkflow.yml
    with:
      artifact_name: playwright-report

  report:
    needs: [set-up_test, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying ${{ toJson(github) }}"
