name: Reusable - Merge Reports & Notify
on:  #We use workflow_call to make this workflow accessible in another workflows
    workflow_call:
        inputs:
            artifact_name:
                description: 'Pattern for blob artifacts'
                required: false
                default: dist
                type: string
            node-version:
                description: 'Define Node version'
                required: true
                type: string
                default: '24'
            retentionDays:
                required: false
                type: number
                default: 30

        outputs:
            report-url:
                description: 'Download URL of merged report'
                value: ${{ jobs.merge-report.outputs.url }}
jobs:
    merge-report:
        runs-on: ubuntu-latest
        outputs:
            url: ${{ steps.allure-upload.outputs.artifact-url }}
        steps:
           - uses: actions/checkout@v6

           - name: Download all blob reports
             uses: actions/download-artifact@v7
             with:
                path: all-blob-reports/
                pattern: ${{ inputs.artifact_name }}-*
                merge-multiple: true

           #- name: Convert to HTML report
            # run: npx playwright merge-reports --reporter=html ./all-blob-reports

           #- name: Upload merged reports
            # id: upload
            # uses: actions/upload-artifact@v4.6.2
            # with:
            #    path: playwright-report/
            #    retention-days: 7

            # Generating the Allure report from Blob reports generated
           - name: Merge into Allure Results
             run: npx playwright merge-reports --reporter=allure-playwright ./all-blob-reports

           - name: Generate Allure HTML Report
             run: npx allure generate ./allure-results --clean -o ./allure-report

           - name: Upload Allure Report
             id: allure-upload
             uses: actions/upload-artifact@v4.6.2
             if: ${{ !cancelled() }}
             with:
                name: allure-report
                path: allure-report/
                retention-days: ${{ inputs.retentionDays }}
